name: make-all

on:
  pull_request:
    paths:
      - .github/actions/setup-elixir/**
      - .github/workflows/**
      - Makefile
      - README.md
      - elixir/**
      - scripts/**
  push:
    branches:
      - main
    paths:
      - .github/actions/setup-elixir/**
      - .github/workflows/**
      - Makefile
      - README.md
      - elixir/**
      - scripts/**

permissions:
  contents: read

concurrency:
  group: make-all-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  make-all:
    uses: ./.github/workflows/_elixir-command.yml
    with:
      artifact-name: make-all
      cache-scope: make-all
      command: make all
      timeout-minutes: 35
    secrets: inherit
